### PR TITLE
Add sitemap

### PR DESCRIPTION
**Pull request by ThiagoDallacqua**
I've read the really short documentation of the `gatsby-plugin-google-analytics` and settled the basic configuration. After running the `npm run build` the respective `sitemap.xml` were created successfully.

I've also read [this guide](https://searchenginewatch.com/sew/how-to/2048706/the-site-map-gateway-optimization) and tried to add the rest of the configuration to the plugin, but couldn't manage to do it so far.

Here's how I've tried:

```
module.exports = {
  siteMetadata: {
    siteUrl: `https://www.murcul.com`,
    lastmod: '2017-12-13',
    changefreq: 'monthly',
    priority: 1
  },
  plugins: [
    `gatsby-plugin-styled-components`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: "UA-109513799-1"
      }
    },
    {
      resolve: `gatsby-plugin-sitemap`
    }
  ]
};
```

and

```
module.exports = {
  siteMetadata: {
    siteUrl: `https://www.murcul.com`,
  },
  plugins: [
    `gatsby-plugin-styled-components`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: "UA-109513799-1"
      }
    },
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        lastmod: "2017-12-13",
        changefreq: "monthly",
        priority: 1
      }
    }
  ]
};
```

Both didn't work.

### CODE REVIEW

**Comment by ziahamza** [comment]
@ThiagoDallacqua Looks like gatsby sitemap isn't that customizable. They have hardcoded values for priority / changefreq in their codebase: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sitemap/src/internals.js#L41

Lets merge this for now, once the merge conflicts are resolved. Later on, we can contribute directly to the sitemap plugin to make it more customizable and use it internally.

**Comment by ziahamza** [comment]
@ThiagoDallacqua Looks like gatsby sitemap isn't that customizable. They have hardcoded values for priority / changefreq in their codebase: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sitemap/src/internals.js#L41

Lets merge this for now, once the merge conflicts are resolved. Later on, we can contribute directly to the sitemap plugin to make it more customizable and use it internally.

**Comment by ThiagoDallacqua** [comment]
that's odd, I've resolved the conflicts, as you can see in the [2a1ff3c](https://github.com/murcul/www.murcul.com/pull/17/commits/2a1ff3caf43ecbe16cc0cf897f6773f5052105b4), but it still counts as if I didn't. Is that because I don't have `write access`?

**Comment by ziahamza** [comment]
@ThiagoDallacqua yea there was a permissions issue. Should be fixed now :)

**Pull request merged**
